### ISSUE TITLE
jmeter 3 support

### ISSUE THREAD

**Issue by wyardley** [dduvnjak/puppet-jmeter#10]
Has anyone tested this with Jmeter 3? 3.x seems to be the default version if you go to the Jmeter site. I would be happy to try to submit a PR to update things to 3.x (or make version configurable) if there hasn't been work done on this.

It seems like there are also no binary packages for RedHat and related distros.

**Comment by dduvnjak** [comment]
@wyardley haven't tested it yet with JMeter 3, been meaning but didn't get a chance yet. A PR would be more than welcome.

**Comment by wyardley** [comment]
@dduvnjak Awesome, this is something I need, so may take a stab at it.
Would you want just a straight update to 3, or a parameter that controls whether to install 2.x / 3.x?

**Comment by wyardley** [comment]
@dduvnjak 
I checked, and from what our folks who use jmeter said, it sounds like the archive files of plugin sets are deprecated in favor of plugin manager, and that there won't be more old style releases after 1.4.0.

So, thus far, what I've been working on is shaping up to be a pretty major shift, and would also not be fully backwards-compatible in terms of the module parameters (that said, while I haven't tested it, I think it could still be backwards compatible with jmeter 2). This is still in progress, but you can see what I have so far at:

https://github.com/wyardley/puppet-jmeter/tree/jmeter_3

Let me know if it's looking to be too drastic a change. I'm hoping to improve test coverage at least a little as well.

**Comment by dduvnjak** [comment]
@wyardley 
That looks good, will test it as soon as I get a chance. 

> and would also not be fully backwards-compatible in terms of the module parameters
I wouldn't worry too much about backwards compatibility, especially if v2 is covered.

Thanks!

**Comment by wyardley** [comment]
@dduvnjak thanks!
btw, I still haven't submitted a PR because it's still in progress. As it is now, it should be working in terms of installing the module and the plugin manager, however, making it so an array of plugins can be specified and installed will be a bit trickier, will probably need to use types / providers.

I switched to `validate_legacy` to try and suppress some warnings, but didn't yet switch to data types; if we want to explicitly drop support for the EOLed Puppet versions <4, I could look at switching.
